export enum CourseLevelEnum {
  Parvulo = -3,
  Prejardin = -2,
  Jardin = -1,
  Transicion = 0,
  Primero = 1,
  Segundo = 2,
  Tercero = 3,
  Cuarto = 4,
  Quinto = 5,
  Sexto = 6,
  Septimo = 7,
  Octavo = 8,
  Noveno = 9,
  Decimo = 10,
  Undecimo = 11,
  PreUniversitario = 12,
  "Ciclo I" = 13,
  "Ciclo II" = 14,
  "Ciclo III" = 15,
  "Ciclo IV" = 16,
  "Ciclo V (Sem. 1)" = 17,
  "Ciclo VI (Sem. 1)" = 18,
  "Ciclo V (Sem. 2)" = 19,
  "Ciclo VI (Sem. 2)" = 20,
  DEFAULT = "-",
}