query GenerateStudentsListUndeterminated($generateStudentsListUndeterminatedInput: GenerateStudentsListUndeterminatedInput) {
  generateStudentsListUndeterminated(generateStudentsListUndeterminatedInput: $generateStudentsListUndeterminatedInput) {
    report_content
  }
}