query GenerateStudentEnrollmentReportI($idStudent: Int) {
  generateStudentEnrollmentReportI(id_student: $idStudent) {
    report_content
  }
}
query GenerateStudentEnrollmentReportII($idStudent: Int) {
  generateStudentEnrollmentReportII(id_student: $idStudent) {
    report_content
  }
}