query GenerateAchievementsAndIndicators($generateAchievementsAndIndicators: GenerateAchievementsAndIndicators) {
  generateAchievementsAndIndicators(generateAchievementsAndIndicators: $generateAchievementsAndIndicators) {
    report_content
  }
}