query GenerateStudentsListDeterminated($generateStudentsListDeterminatedInput: GenerateStudentsListDeterminatedInput) {
  generateStudentsListDeterminated(generateStudentsListDeterminatedInput: $generateStudentsListDeterminatedInput) {
    report_content
  }
}