query Achievements($filterAchievementInput: FilterAchievementInput) {
  achievements(filterAchievementInput: $filterAchievementInput) {
    id_achievement
    id_course
    period
    description
  }
}