query Courses($filterCourseInput: FilterCourseInput) {
  courses(filterCourseInput: $filterCourseInput) {
    id_course
    id_group
    id_area
    id_teacher
    teacher {
      name
      last_name
    }
    name
    position
    dimension_code
    dimension_type
    hour
    average
    percentage
  }
}
