query GetStudentsByGroup($idGroup: Int!) {
  studentsByGroup(id_group: $idGroup) {
    id_student
    name
    last_name
    type_id
    identification
    sex
    direction
    phone
    guardian
    status
    birthday
    father
    mother
    email
  }
}